security:
    encoders:
        Study\BlogBundle\Document\User : sha512
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_EDITOR
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        my_mongo_provider:
            mongodb: {class: Study\BlogBundle\Document\User, property: username}
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true
            
        backend:
            pattern: ^/admin/*
            provider: my_mongo_provider
            form_login:
                check_path: /login_check
                login_path: /login
                default_target_path: /post
            logout:
                path:   /logout
                target: /post
                invalidate_session: false
            anonymous:    true
            remember_me:
                key:      "%secret%"
                lifetime: 3600
                path:     /
                domain:   ~
                remember_me_parameter: _remember_me

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/user, role: ROLE_ADMIN }
        - { path: ^/backend/post/add, roles: ROLE_EDITOR }
        - { path: ^/backend/post/edit/*, roles: ROLE_EDITOR }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }