security:
    encoders:
        Study\BlogBundle\Document\User : sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_EDITOR

    providers:
        my_mongo_provider:
            mongodb: {class: Study\BlogBundle\Document\User, property: username}

    firewalls:
        backend:
            pattern: ^/.*
            provider: my_mongo_provider
            form_login:
                check_path: /login_check
                login_path: /login
                default_target_path: /
            logout:
                path:   /logout
                target: /
                invalidate_session: false
            anonymous:    true
            remember_me:
                key:      "%secret%"
                lifetime: 3600
                path:     /
                domain:   ~
                remember_me_parameter: _remember_me

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user, role: ROLE_ADMIN }
        - { path: ^/backend/post/add, roles: ROLE_EDITOR }
        - { path: ^/backend/post/edit/*, roles: ROLE_EDITOR }
        - { path: ^/admin, roles: ROLE_ADMIN }