parameters:
#    study_blog.example.class: Study\BlogBundle\Example

services:
#    study_blog.example:
#        class: %study_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    study_blog_user.password_resetting:
      class: Study\BlogBundle\EventListener\PasswordResettingListener
      arguments: ["@router"]
      tags:
        - { name: kernel.event_subscriber }
    
    study_user.registration.form.type:
      class: Study\BlogBundle\Form\Type\RegistrationFormType
      arguments: [%fos_user.model.user.class%]
      tags:
        - { name: form.type, alias: study_user_registration }
      