<?php

namespace Study\BlogBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends DocumentRepository
{
	public function findAllQueryBuilder()
	{
		return $this->createQueryBuilder()
				->sort('title', 'ASC')
				->setQueryArray(array('deleted' => false))
				->getQuery()
				->execute();
	}
}