parameters:
#    study_user.example.class: Study\UserBundle\Example

services:
#    study_user.example:
#        class: %study_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
